### ISSUE TITLE
Fragments

### ISSUE THREAD

**Issue by iYaroslav** [atulmy/gql-query-builder#18]
Can I use fragments?

https://graphql.org/learn/queries/#fragments

**Comment by atulmy** [comment]
At the moment it's not supported. If you think you can spare time to contribute, feel free to go ahead and send a pull request!

**Comment by toadkicker** [comment]
The adapter is basically a bunch of fragments of template being assembled together. I don't see why one couldn't just write it such:

```
const adapterInstance = new CustomAdapter({withFragments: ['fnName', 'fnName2']})
query(options, adapterInstance)
```

Then in the adapter class can just check if `fnName` exists, and call it when appropriate it.

Just my quick thought/hack about it.

**Comment by atulmy** [comment]
@iYaroslav you can follow @toadkicker's example until we bake in `Fragments` out of the box.

**Comment by toadkicker** [comment]
I think to do that it would be helpful to have a bit of a formalized life cycle for an adapter that includes a better look at features like fragment injection.

**Comment by MaxResolution** [comment]
I would love to have this feature as well

**Comment by ARHariri** [comment]
I don't see the purpose of using `Adapter` (especially to handle fragment). When a user defines and passes an adapter as the second argument, he should write all logic of generating query instead of specifying his especial logic that should be replaced some parts of the default code, because of instantiating from user-defined adapter class and then pass the controller to that instance to handle all flow of generating a query.
I think defining and using an adapter equals defining a new package to generate a GraphQL query.
So it seems using an adapter is not useful unless fixing adapter usage with one of the three following approaches:
1- Use `method overriding` approach of OOP (It seems the intention of using an adapter is this, but as `DefaultQueryAdapter` is not exposed, user should implement adapter from scratch)
2- Accept function (or a config) as an adapter instead of class. In this way 1) highly recommended to follow functional programming approach instead of OOP in the codebase and 2) get a config (instead of function) that defines logic to generate a query based on the passed options.

**Comment by IAmNatch** [comment]
For **[Inline Fragments](https://graphql.org/learn/queries/#inline-fragments)** I found I was able to create the nessesary queries by using dynamic object keys. 

For example to generate the following query:
```
{
  page {
    id
    ... on HomePage {
      content {
        blockType
      }
    }
  }
}
```

I wrote the following query:
```
const query = gql.query({
  operation: "page",
  fields: [
    "id",
    {
      "... on HomePage": [{
        content: [
          "blockType"
        ]
      }],
    }
  ]
});
```

This was great news for me. Thanks for building this awesome utility!
