### ISSUE TITLE
handling undefined datatype

### ISSUE THREAD

**Issue by derit** [atulmy/gql-query-builder#23]
when variable is undefined return a error 
how to handling this error ?

**Comment by ARHariri** [comment]
I don't think you need to pass the undefined variable. If your query accepts the undefined variable you can ignore it unless it has value.
Please filter variables before passing them to generate query

**Comment by ARHariri** [comment]
When you set a variable to an undefined like this
```
  variables: {
    email: undefined
  }
```
you get an error because the generator cannot infer the type of variable to set it. But when you assign your variable by an object value and set the `value` property to an undefined, like this
```
  variables: {
    email: { value: undefined }
  }
```
you have not got an error whether you set `type` property or not (The default `type` is `String`)
